homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

mqtt:
  embedded:

#hdmi_cec:
#  platform: media_player

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

ios:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

light:
#  - platform: piglow
  - platform: hue

camera:
  - platform: uvc
    nvr: !secret nvr_ip
    key: !secret uvc_key

device_tracker: !include device_tracker.yaml

ecobee:
  api_key: !secret ecobee_api

media_player: !include media_player.yaml

updater:

# Discover some devices automatically
discovery:
  ignore:
    - roku

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Include sensors
sensor: !include sensor.yaml

# Text to speech
tts:
  platform: google

# Include Groups
group: !include groups.yaml

# Include Automation
automation: !include automations.yaml

# Include Notification Setup
notify: !include notify.yaml

# Include Zone info
zone: !include_dir_list zones

# Include Alexa Intents
alexa:
  intents: !include_dir_named alexa_intents/
  flash_briefings: !include_dir_named alexa_flash_briefings/

# Include Locks
lock: !include locks.yaml

# Include booleans
input_boolean: !include_dir_named booleans

# Binary Sensors
binary_sensor:
  - platform: workday
    country: US
