- platform: unifi
  host: !secret unifi_hostname
  port: 443
  username: !secret unifi_username
  password: !secret unifi_password
  track_new_devices: false
- platform: icloud
  username: !secret icloud_username
  password: !secret icloud_password
