- platform: plex
  entity_namespace: 'plex'
  use_custom_entity_ids: true
  use_episode_art: true
- platform: cast
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
